--
-- ALTER TABLE `smarthealthc`.`activity_record`
-- DROP COLUMN `duration`;
--
-- ALTER TABLE `smarthealthc`.`activity_record`
-- DROP COLUMN `status`;
--
-- ALTER TABLE `smarthealthc`.`activity_record`
-- DROP COLUMN `type`;
--
-- ALTER TABLE `smarthealthc`.`app_user`   DROP  COLUMN `hospital_number`;
--
-- ALTER TABLE `smarthealthc`.`cardinal_record`   DROP  COLUMN `type_cardinal_index`;
--
-- ALTER TABLE `smarthealthc`.`cardinal_record`   DROP  COLUMN `value`;
--
-- ALTER TABLE `smarthealthc`.`forget_password_code`  DROP  COLUMN `is_used`;
--
-- ALTER TABLE `smarthealthc`.`lesson`  DROP  COLUMN `text`;